version: '3.8'

services:
  tgtime-notifier-app:
    image: ghcr.io/tgtime-notifier:master
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: tgtime-notifier-app
    ports:
      - "1122:8080"
    networks:
      - tgtime-notifier-network

networks:
  tgtime-notifier-network:
    driver: bridge