global:
  scrape_interval:     2s
  evaluation_interval: 2s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [":9090"]

  - job_name: "app"
    static_configs:
      - targets: ["app:2112"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]