// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package telegram

//go:generate minimock -i github.com/robertobadjio/tgtime-notifier/internal/service/notifier/telegram.botAPI -o bot_api_mock.go -n BotAPIMock -p telegram

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	TGBotAPI "github.com/go-telegram-bot-api/telegram-bot-api"
	"github.com/gojuno/minimock/v3"
)

// BotAPIMock implements botAPI
type BotAPIMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSend          func(c TGBotAPI.Chattable) (m1 TGBotAPI.Message, err error)
	funcSendOrigin    string
	inspectFuncSend   func(c TGBotAPI.Chattable)
	afterSendCounter  uint64
	beforeSendCounter uint64
	SendMock          mBotAPIMockSend
}

// NewBotAPIMock returns a mock for botAPI
func NewBotAPIMock(t minimock.Tester) *BotAPIMock {
	m := &BotAPIMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMock = mBotAPIMockSend{mock: m}
	m.SendMock.callArgs = []*BotAPIMockSendParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mBotAPIMockSend struct {
	optional           bool
	mock               *BotAPIMock
	defaultExpectation *BotAPIMockSendExpectation
	expectations       []*BotAPIMockSendExpectation

	callArgs []*BotAPIMockSendParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BotAPIMockSendExpectation specifies expectation struct of the botAPI.Send
type BotAPIMockSendExpectation struct {
	mock               *BotAPIMock
	params             *BotAPIMockSendParams
	paramPtrs          *BotAPIMockSendParamPtrs
	expectationOrigins BotAPIMockSendExpectationOrigins
	results            *BotAPIMockSendResults
	returnOrigin       string
	Counter            uint64
}

// BotAPIMockSendParams contains parameters of the botAPI.Send
type BotAPIMockSendParams struct {
	c TGBotAPI.Chattable
}

// BotAPIMockSendParamPtrs contains pointers to parameters of the botAPI.Send
type BotAPIMockSendParamPtrs struct {
	c *TGBotAPI.Chattable
}

// BotAPIMockSendResults contains results of the botAPI.Send
type BotAPIMockSendResults struct {
	m1  TGBotAPI.Message
	err error
}

// BotAPIMockSendOrigins contains origins of expectations of the botAPI.Send
type BotAPIMockSendExpectationOrigins struct {
	origin  string
	originC string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSend *mBotAPIMockSend) Optional() *mBotAPIMockSend {
	mmSend.optional = true
	return mmSend
}

// Expect sets up expected params for botAPI.Send
func (mmSend *mBotAPIMockSend) Expect(c TGBotAPI.Chattable) *mBotAPIMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("BotAPIMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &BotAPIMockSendExpectation{}
	}

	if mmSend.defaultExpectation.paramPtrs != nil {
		mmSend.mock.t.Fatalf("BotAPIMock.Send mock is already set by ExpectParams functions")
	}

	mmSend.defaultExpectation.params = &BotAPIMockSendParams{c}
	mmSend.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSend.expectations {
		if minimock.Equal(e.params, mmSend.defaultExpectation.params) {
			mmSend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSend.defaultExpectation.params)
		}
	}

	return mmSend
}

// ExpectCParam1 sets up expected param c for botAPI.Send
func (mmSend *mBotAPIMockSend) ExpectCParam1(c TGBotAPI.Chattable) *mBotAPIMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("BotAPIMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &BotAPIMockSendExpectation{}
	}

	if mmSend.defaultExpectation.params != nil {
		mmSend.mock.t.Fatalf("BotAPIMock.Send mock is already set by Expect")
	}

	if mmSend.defaultExpectation.paramPtrs == nil {
		mmSend.defaultExpectation.paramPtrs = &BotAPIMockSendParamPtrs{}
	}
	mmSend.defaultExpectation.paramPtrs.c = &c
	mmSend.defaultExpectation.expectationOrigins.originC = minimock.CallerInfo(1)

	return mmSend
}

// Inspect accepts an inspector function that has same arguments as the botAPI.Send
func (mmSend *mBotAPIMockSend) Inspect(f func(c TGBotAPI.Chattable)) *mBotAPIMockSend {
	if mmSend.mock.inspectFuncSend != nil {
		mmSend.mock.t.Fatalf("Inspect function is already set for BotAPIMock.Send")
	}

	mmSend.mock.inspectFuncSend = f

	return mmSend
}

// Return sets up results that will be returned by botAPI.Send
func (mmSend *mBotAPIMockSend) Return(m1 TGBotAPI.Message, err error) *BotAPIMock {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("BotAPIMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &BotAPIMockSendExpectation{mock: mmSend.mock}
	}
	mmSend.defaultExpectation.results = &BotAPIMockSendResults{m1, err}
	mmSend.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSend.mock
}

// Set uses given function f to mock the botAPI.Send method
func (mmSend *mBotAPIMockSend) Set(f func(c TGBotAPI.Chattable) (m1 TGBotAPI.Message, err error)) *BotAPIMock {
	if mmSend.defaultExpectation != nil {
		mmSend.mock.t.Fatalf("Default expectation is already set for the botAPI.Send method")
	}

	if len(mmSend.expectations) > 0 {
		mmSend.mock.t.Fatalf("Some expectations are already set for the botAPI.Send method")
	}

	mmSend.mock.funcSend = f
	mmSend.mock.funcSendOrigin = minimock.CallerInfo(1)
	return mmSend.mock
}

// When sets expectation for the botAPI.Send which will trigger the result defined by the following
// Then helper
func (mmSend *mBotAPIMockSend) When(c TGBotAPI.Chattable) *BotAPIMockSendExpectation {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("BotAPIMock.Send mock is already set by Set")
	}

	expectation := &BotAPIMockSendExpectation{
		mock:               mmSend.mock,
		params:             &BotAPIMockSendParams{c},
		expectationOrigins: BotAPIMockSendExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSend.expectations = append(mmSend.expectations, expectation)
	return expectation
}

// Then sets up botAPI.Send return parameters for the expectation previously defined by the When method
func (e *BotAPIMockSendExpectation) Then(m1 TGBotAPI.Message, err error) *BotAPIMock {
	e.results = &BotAPIMockSendResults{m1, err}
	return e.mock
}

// Times sets number of times botAPI.Send should be invoked
func (mmSend *mBotAPIMockSend) Times(n uint64) *mBotAPIMockSend {
	if n == 0 {
		mmSend.mock.t.Fatalf("Times of BotAPIMock.Send mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSend.expectedInvocations, n)
	mmSend.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSend
}

func (mmSend *mBotAPIMockSend) invocationsDone() bool {
	if len(mmSend.expectations) == 0 && mmSend.defaultExpectation == nil && mmSend.mock.funcSend == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSend.mock.afterSendCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSend.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Send implements botAPI
func (mmSend *BotAPIMock) Send(c TGBotAPI.Chattable) (m1 TGBotAPI.Message, err error) {
	mm_atomic.AddUint64(&mmSend.beforeSendCounter, 1)
	defer mm_atomic.AddUint64(&mmSend.afterSendCounter, 1)

	mmSend.t.Helper()

	if mmSend.inspectFuncSend != nil {
		mmSend.inspectFuncSend(c)
	}

	mm_params := BotAPIMockSendParams{c}

	// Record call args
	mmSend.SendMock.mutex.Lock()
	mmSend.SendMock.callArgs = append(mmSend.SendMock.callArgs, &mm_params)
	mmSend.SendMock.mutex.Unlock()

	for _, e := range mmSend.SendMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.err
		}
	}

	if mmSend.SendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSend.SendMock.defaultExpectation.Counter, 1)
		mm_want := mmSend.SendMock.defaultExpectation.params
		mm_want_ptrs := mmSend.SendMock.defaultExpectation.paramPtrs

		mm_got := BotAPIMockSendParams{c}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.c != nil && !minimock.Equal(*mm_want_ptrs.c, mm_got.c) {
				mmSend.t.Errorf("BotAPIMock.Send got unexpected parameter c, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSend.SendMock.defaultExpectation.expectationOrigins.originC, *mm_want_ptrs.c, mm_got.c, minimock.Diff(*mm_want_ptrs.c, mm_got.c))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSend.t.Errorf("BotAPIMock.Send got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSend.SendMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSend.SendMock.defaultExpectation.results
		if mm_results == nil {
			mmSend.t.Fatal("No results are set for the BotAPIMock.Send")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmSend.funcSend != nil {
		return mmSend.funcSend(c)
	}
	mmSend.t.Fatalf("Unexpected call to BotAPIMock.Send. %v", c)
	return
}

// SendAfterCounter returns a count of finished BotAPIMock.Send invocations
func (mmSend *BotAPIMock) SendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.afterSendCounter)
}

// SendBeforeCounter returns a count of BotAPIMock.Send invocations
func (mmSend *BotAPIMock) SendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.beforeSendCounter)
}

// Calls returns a list of arguments used in each call to BotAPIMock.Send.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSend *mBotAPIMockSend) Calls() []*BotAPIMockSendParams {
	mmSend.mutex.RLock()

	argCopy := make([]*BotAPIMockSendParams, len(mmSend.callArgs))
	copy(argCopy, mmSend.callArgs)

	mmSend.mutex.RUnlock()

	return argCopy
}

// MinimockSendDone returns true if the count of the Send invocations corresponds
// the number of defined expectations
func (m *BotAPIMock) MinimockSendDone() bool {
	if m.SendMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendMock.invocationsDone()
}

// MinimockSendInspect logs each unmet expectation
func (m *BotAPIMock) MinimockSendInspect() {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BotAPIMock.Send at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendCounter := mm_atomic.LoadUint64(&m.afterSendCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && afterSendCounter < 1 {
		if m.SendMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BotAPIMock.Send at\n%s", m.SendMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BotAPIMock.Send at\n%s with params: %#v", m.SendMock.defaultExpectation.expectationOrigins.origin, *m.SendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && afterSendCounter < 1 {
		m.t.Errorf("Expected call to BotAPIMock.Send at\n%s", m.funcSendOrigin)
	}

	if !m.SendMock.invocationsDone() && afterSendCounter > 0 {
		m.t.Errorf("Expected %d calls to BotAPIMock.Send at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendMock.expectedInvocations), m.SendMock.expectedInvocationsOrigin, afterSendCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *BotAPIMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *BotAPIMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *BotAPIMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendDone()
}
