name: TgTime Notifier Audit

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    audit:
        strategy:
            matrix:
                go-version: [1.23.x]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: ${{ matrix.go-version }}

            - name: Verify dependencies
              run: go mod verify

            - name: Build
              run: go build -v ./...

            - name: Run go vet
              run: go vet ./...

            - name: Run test
              run: go test ./internal/... -count=1 -race

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.64.5
                args: --timeout=30m --config=./.golangci.pipeline.yaml