name: TgTime Notifier Test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        strategy:
            matrix:
                go-version: [1.23.x]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: ${{ matrix.go-version }}

            - name: Add config
              run: |
                touch ./.env

            - name: Build containers
              env:
                BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
              run: docker run -e HTTP_PORT='8081' -e BOT_TOKEN="$SUPER_SECRET" -e WEBHOOK_PATH=${{ secrets.WEBHOOK_PATH }} -e WEBHOOK_LINK=${{ secrets.WEBHOOK_LINK }} -e PROMETHEUS_APP_PORT='2112' $(docker build -q .)

            - name: Start containers
              run: docker compose -f docker-compose.yml -f docker-compose.yml up -d

            #- name: Health check
              #run: |
                #docker run --network container:tgtime-notifier-ap appropriate/curl -s --retry 10 --retry-connrefused --retry-delay 5 --retry-max-time 30 http://localhost:8080/ping

            - name: Stop containers
              if: always()
              run: docker compose -f docker-compose.yml -f docker-compose.yml down